import streamlit as st

AZURE_OPENAI_ENDPOINT    = st.secrets["AZURE_OPENAI_ENDPOINT"]
AZURE_OPENAI_KEY         = st.secrets["AZURE_OPENAI_KEY"]
AZURE_OPENAI_DEPLOYMENT  = st.secrets["AZURE_OPENAI_DEPLOYMENT"]
AZURE_OPENAI_API_VERSION = "2024-02-15-preview"